### ISSUE TITLE
Channel close need reconnection

### ISSUE THREAD

**Issue by icpd** [pmorelli92/bunnify#23]
The channel may be closed due to some unexpected circumstances, and in this case, the handling of rebuilding the channel is also necessary.

**Comment by pmorelli92** [comment]
Hi @icpd can you please share a little bit more of context on the issue you are facing?

As the library works right now, unless I've fucked up, is that if a channel is closed for some reason, then the consumer will get another channel from the connection. So I don't see the issue here. Can you please help me help you?

**Comment by pmorelli92** [comment]
So basically, as you can see here: https://github.com/pmorelli92/bunnify/blob/main/bunnify/consumerLoop.go

The for loop of deliveries will exit when the channel is broken, then we check if the channel is closed, if not we close it not to leak it. Then the `consumer.Consume` will be called getting a new channel from the connection (unless the connection was closed voluntarily)

**Comment by icpd** [comment]
Sorry, I didn't look closely enough before. Indeed, the current handling method is fine.
