### ISSUE TITLE
Add option for requeue if it fails

### ISSUE THREAD

**Issue by tomaswarynyca** [pmorelli92/bunnify#29]
@pmorelli92 I have a case where if the event fails a requeue of the message has to be done.
how do you think this problem can be solved?
add one more option to the event metadata or some config in the consumer?

**Comment by pmorelli92** [comment]
Hi @tomaswarynyca ! I just had time to check out on this issue and the PR you did. First, thanks for the effort of collaborating into this lib, I really appreciate this.

In the current state of the library the only supported way to retry a message is the following:

https://github.com/pmorelli92/bunnify/blob/7d9a8000041c0041e4338e5e6cf004f7a277fb47/tests/dead_letter_receives_event_test.go#L34-L55

In this scenario:

- Consumer defines an event handler.
- Consumer defines a dead letter queue for events that fail to consume.
- Publisher publishes an event.
- Consumer's handler fails on the event.
- Consumer's dead letter handler gets the event.

The common scenario here is that the dead letter handler will save this event somewhere, so you can inspect and retry this later on. The retry will not happen automatically so you will need another piece of code that will publish this message again into the queue.

---

Now, if what you want is still an automatic retry mechanism we can for sure do that, but I would like to consider the following:

- The consumer needs to take care of this rather than the publisher as it is responsibility of the one handling the event.
- RabbitMQ quorum queues is already supporting [poisoning messages](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling).
- Then we can make so that there is another option `bunnify.WithRetries(retries int)` that only works when used together with quorum queue. 

In the snippet below:

https://github.com/pmorelli92/bunnify/blob/ccefb5170f60a6a9c40925e6d19f6681820cf8f2/consumer.go#L125

- We could set the `delivery-limit` to the number of retries. 
- Then on the `nack` we only set requeue to true only if the number of retries is greater than 0 (as the consumer configured retried mechanism)
- Add tests to cover this new functionality.

--- 

I can do this today / tomorrow if that is fine for you, or if you want to do it yourself you are more than welcomed to do so and I will be reviewing the code as I have time :)

**Comment by tomaswarynyca** [comment]
@pmorelli92 thank you for the explanation of your point of view.
Just updated the PR by adding retries to the consumer options.
I'm missing the tests, I'll leave this part to you who are fresher with this development.

**Comment by pmorelli92** [comment]
All right, I will work on that part then.

**Comment by pmorelli92** [comment]
You can now try `go get github.com/pmorelli92/bunnify@v0.0.4-pre-2` and tell me if it worked :)

**Comment by tomaswarynyca** [comment]
Ohh nice! :+1: 
I have just tested it and it works perfectly, thank you!
