### ISSUE TITLE
Add delay to message

### ISSUE THREAD

**Issue by tomaswarynyca** [pmorelli92/bunnify#45]
Any idea how to delay messages to be proccesed?

Adding this plugin would be the only option?
https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq

**Comment by pmorelli92** [comment]
> Adding this plugin would be the only option?

In what RabbitMQ is aware, I think it is. In some previous workplace what I've done to solve this was to store the messages in a database table and loop through them, only firing them at the correct time.

But if you want to go with the plugin approach, we can probably extend how the Publish looks like in order to accept an option such as `WithHeader(key, val)` to add custom headers to the publish function.

**Comment by tomaswarynyca** [comment]
Hi - I'm checking how outbox works, how can I add messages with delay?
I understand that there should be an option in PublishableEvent that allows to configure Timestamp and modify the query to only get events less than the current time per CreatedAt.

**Comment by pmorelli92** [comment]
Hi @tomaswarynyca , yes there is no support in lib for delay messages. You can always check out something like this on the [RabbitMQ plugins](https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq)

**Comment by tomaswarynyca** [comment]
Yes, I was looking into that option but there is no support in lib for injecting custom headers like x-delay.

**Comment by pmorelli92** [comment]
I can probably add that :)
